### ISSUE TITLE
Seems to not be working for Simulacrum Multiplayer

### ISSUE THREAD

**Issue by idolfan** [mwoiii/stats-plus#15]
Works fine in Singleplayer Simulacrum, but not for multiplayer Simulacrum ( There is no stats button on the result screen ).
Tested with 1 player multiplayer.

**Comment by mwoiii** [comment]
hey, thanks for reporting 🙂

I actually originally intended for the button to not show in simulacrum due to stage changes being very infrequent, but given that it doesn't actually break anything, I've released a patch that removes the code that prevented it from appearing (that only worked in multiplayer lol)

**Comment by idolfan** [comment]
Thanks sir. I often play up to wave 100+, so it is definitely worth it for me :)
